[package]
name = "radical-native"
version = "0.1.0"
edition = "2018"

[dependencies]
byteorder = "1.3.4"
dirs = "2.0.2"
serde = "1.0.104"
serde_json = "1.0.48"
seshat = { git = "https://github.com/stoically/seshat.git", features = ["serde"] }

[dev-dependencies]
tempfile = "3.1.0"
