[package]
name = "radical-native"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.28"
byteorder = "1.3.4"
dirs = "2.0.2"
serde = "1.0.106"
serde_json = "1.0.51"
seshat = { git = "https://github.com/stoically/seshat", branch = "thiserror" }

[dev-dependencies]
tempfile = "3.1.0"

[package.metadata.deb]
depends = ["libsqlcipher0"]
