[package]
name = "riot-web-booster-pack"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
serde = "1.0.104"
serde_json = "1.0.47"
seshat = { git = "https://github.com/stoically/seshat", features = ["encryption", "use-serde"] }
tempfile = "3.1.0"
